---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.crypto
    version: 2.18.0
  - name: containers.podman
    version: 1.12.0
  - name: fedora.linux_system_roles
    version: 1.75.0

roles: []
